const yearValue=document.getElementById('yearValue');if(yearValue)yearValue.textContent=new Date().getFullYear();
const style=document.createElement('style');style.textContent='.hero-visual,.hero-image{position:relative}.reveal{opacity:0;transform:translateY(18px);transition:.7s ease}.reveal.visible{opacity:1;transform:none}';document.head.appendChild(style);
const space=document.createElement('div');space.className='cinematic-space';space.setAttribute('aria-hidden','true');const earth=document.createElement('div');earth.className='earth-globe';earth.setAttribute('aria-hidden','true');document.body.prepend(space,earth);
const header=document.querySelector('.site-header');if(header&&!header.querySelector('.broadcast-bar')){const b=document.createElement('div');b.className='broadcast-bar';b.innerHTML='<span>◉ <strong>LIVE</strong> &nbsp; India-focused web, app & API studio // Ranchi HQ</span><span><a href="tel:+917061899614">☎ +91 7061899614</a></span>';header.prepend(b)}
const layers=[['01','Discovery','Goals, audience, competitors and success metrics aligned before production.'],['02','Brand Strategy','A clear visual direction, voice and memorable positioning for your market.'],['03','UX Architecture','User journeys, sitemap and information architecture that remove friction.'],['04','Interface Design','Responsive, accessible screens with a premium visual system.'],['05','Frontend Engineering','Fast, polished and maintainable web experiences built for every device.'],['06','Backend Systems','Secure APIs, databases and business logic that scale with demand.'],['07','Mobile Experiences','Cross-platform app foundations for iOS and Android products.'],['08','Commerce','Conversion-focused stores, catalogues, payments and order workflows.'],['09','Integrations','CRMs, analytics, payments, maps and third-party services connected cleanly.'],['10','Performance','SEO, Core Web Vitals, caching and image optimization for speed.'],['11','Quality & Security','Testing, backups, monitoring and release checks before launch.'],['12','Growth Partnership','Analytics, experiments, maintenance and support after go-live.']];
const services=document.querySelector('#services');if(services&&!document.querySelector('#layers')){const section=document.createElement('section');section.id='layers';section.className='section layer-section';section.innerHTML='<div class="container"><div class="section-heading reveal"><p class="eyebrow">The 12-layer system</p><h2>More than a website.<br><em>A complete digital engine.</em></h2><p>Every project is strengthened across twelve connected layers so the experience looks great, works reliably and keeps growing.</p></div><div class="layer-grid">'+layers.map(x=>'<article class="layer-card reveal"><span class="layer-number">LAYER '+x[0]+'</span><h3>'+x[1]+'</h3><p>'+x[2]+'</p></article>').join('')+'</div></div>';services.after(section)}
const detailData={banner:{name:'Banner intelligence',subtitle:'Click any highlighted banner icon to open the complete story behind that experience.',features:['Interactive banner controls with keyboard support','Full project, service and feature details in a focused modal','Direct contact CTA to start the selected project','Responsive layout for mobile, tablet and desktop']},mega:{name:'Mega Scale · ₹80,000',subtitle:'A high-performance platform for ambitious teams.',features:['Grade architecture','120GB high-speed storage','Advanced DNS + SSL','24/7 technical squad support','Performance and security optimization']},custom:{name:'Custom App Ecosystem · ₹100,000',subtitle:'A bespoke application foundation with every critical service connected.',features:['Custom app ecosystem','Full block architecture','Global service integrations','Product design and strategy','Launch roadmap and analytics']},ultimate:{name:'Ultimate Command · ₹150,000',subtitle:'Complete ownership of a full-scale web and app infrastructure.',features:['Custom web and app infrastructure','Complete ownership and governance','Lifetime support','Priority launch and optimization','Growth and maintenance partnership']}};
const modal=document.getElementById('planModal'),content=document.getElementById('modalContent');function openDetails(key){const d=detailData[key]||detailData.banner;if(!modal||!content)return;content.innerHTML='<div class="modal-header"><p class="eyebrow">Full details</p><h3 id="modalTitle">'+d.name+'</h3><p class="modal-subtitle">'+d.subtitle+'</p></div><ul class="detail-list">'+d.features.map(f=>'<li>✓ '+f+'</li>').join('')+'</ul><a class="modal-cta" href="#contact" data-modal-contact>Discuss this with us ↗</a>';modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';modal.querySelector('.modal-close')?.focus()}
function closeDetails(){if(!modal)return;modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
const hero=document.querySelector('.hero-image,.hero-visual');if(hero&&!hero.querySelector('.banner-detail-trigger')){const button=document.createElement('button');button.className='banner-detail-trigger';button.type='button';button.innerHTML='<span>✦</span> Banner details';button.addEventListener('click',()=>openDetails('banner'));hero.append(button)}
document.querySelectorAll('[data-plan]').forEach(el=>el.addEventListener('click',e=>openDetails(e.currentTarget.dataset.plan)));modal?.querySelector('.modal-close')?.addEventListener('click',closeDetails);modal?.querySelector('[data-close="true"]')?.addEventListener('click',closeDetails);modal?.addEventListener('click',e=>{if(e.target.matches('[data-modal-contact]'))closeDetails()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetails()});
const items=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});items.forEach(i=>observer.observe(i))}else items.forEach(i=>i.classList.add('visible'));
